baseURL = "https://rkar.org/"
languageCode = "en-us"
DefaultContentLanguage = "en"

paginate = 30

title = "rkar.org"
theme = "tui"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "docs"
summaryLength = 99999999

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/archive"
    weight = 11

  [[menu.main]]
    identifier = "til"
    name = "til"
    url = "/til"
    weight = 12

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 13

  [[menu.main]]
    identifier = "feed"
    name = "feed"
    url = "/archive/index.xml"
    weight = 14

  [[menu.secondary]]
    identifier = "uses"
    name = "uses"
    url = "/uses"
    weight = 10

  [[menu.secondary]]
    identifier = "emacs"
    name = "emacs"
    url = "https://emacs.rkar.org"
    weight = 11
    params.external = true

  [[menu.secondary]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 12

  [[menu.secondary]]
    identifier = "keyboards"
    name = "keyboards"
    url = "https://mrprofessor.dev"
    weight = 13
    params.external = true

[params]
  author = "rkar"
  description = ""
  sitename = "rkar blog"
  github = "https://github.com/mrprofessor"
  twitter = "@weary_beard"
  favicon = "/images/favicon/favicon.ico"
  mainSections = "archive"
  recentArticlesLimit = 3

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'emacs'
    tabWidth = 4

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
