baseURL = "https://rkar.org/"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsStyle = "emacs"
paginate = 30

title = "rkar.org"
theme = "tui"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

publishDir = "docs"
summaryLength = 99999999


[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "articles"
    name = "articles"
    url = "/articles"
    weight = 11

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 12


  [[menu.main]]
    identifier = "uses"
    name = "uses"
    url = "/uses"
    weight = 13

  [[menu.main]]
    identifier = "til"
    name = "til"
    url = "/til"
    weight = 14

  [[menu.main]]
    identifier = "keyboards"
    name = "keyboards"
    url = "https://mrprofessor.dev"
    weight = 15
    [menu.main.params]
        external = true

  [[menu.main]]
    identifier = "feed"
    name = "feed"
    url = "/articles/index.xml"
    weight = 16

[params]
  author = "rkar"
  description = ""
  sitename = "rkar blog"
  github = "https://github.com/mrprofessor"
  twitter = "@weary_beard"
  favicon = "/images/favicon.ico"
  mainSections = "articles"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']